name: Deploy Backend (Prod)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Versión utilizada por defecto en AWS Lambda

      - name: Install Node dependencies
        run: npm install

      - name: Install Python dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run Tests
        run: pytest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Parse and Load .env
        run: |
          echo "${{ secrets.ENV_FILE_PROD }}" > .env
          # Opcional: Inyectar las variables directamente al entorno de GitHub Actions (por si otro script las necesita)
          while IFS= read -r line || [ -n "$line" ]; do
            if [[ -n "$line" && "$line" != \#* ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < .env

      - name: Serverless Deploy
        run: npx sls deploy --stage prod --alias current
